### ISSUE TITLE
[Docker Image] Failed to initialize PostgreSQL DB

### ISSUE THREAD

**Issue by smilehappy126** [FraunhoferIOSB/FROST-Server#1821]
Hi,
    I've encountered some issues from building docker container from official image.
    If I directly use STA v1.1 after `docker-compose up -d` I will received error message as below:
14:44:54.318 [http-nio-8080-exec-1] ERROR d.f.i.i.f.p.p.u.ConnectionUtils - Could not inizialize de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.utils.ConnectionUtils$ConnectionWrapper
java.sql.SQLException: Cannot create PoolableConnectionFactory (Connection to sta_one_PG:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
14:44:54.647 [http-nio-8080-exec-1] INFO     d.f.i.i.f.p.p.ResultBuilder - Failed to run query:
select "e0"."ID", "e0"."PROPERTIES", "e0"."NAME", "e0"."DESCRIPTION" from "THINGS" as "e0" order by "e0"."ID" asc offset 0 rows fetch next 101 rows only
14:44:54.647 [http-nio-8080-exec-1] ERROR      d.f.i.i.f.service.Service - Failed to handle request (details in debug): Failed to run query: Cannot execute query. No JDBC Connection configured

However, if I switch to STA v1.0 then JDBC connection is fine and v1.1 is fixed as well. How's this possible?

Thanks in advance!

**Comment by hylkevds** [comment]
The database server was probably not started yet. The first time PostgreSQL takes a bit longer to start.

**Comment by hylkevds** [comment]
I've improved the docker-compose files so that FROST waits till the database is fully ready.

**Comment by smilehappy126** [comment]
Hi,
  This issue seems to appear again. Sometime I can access /v1.1 directly sometime I cannot. Sometime /v1.1/Things will respond 500 sometime it has to wait for around 5 second to initialize and respond correct content.
I'm using Java code to make Http Connect to the server.

**Comment by smilehappy126** [comment]
Additional info:
(1) Human using browser - takes two times GET Request to successfully initialize
(2) Java code - takes six times(with each time sleep for 5 seconds) GET Request to successfully initialize

**Comment by hylkevds** [comment]
Checking the database and initialising FROST can take a bit, especially on a slow database.
But database check only needs to run once for every FROST version update, so you should set `persistence.autoUpdateDatabase` to `false`.
Unless you have a different issue with your database, and this is not about first-start, but I can't determine that from your limited description.

**Comment by smilehappy126** [comment]
```persistence.autoUpdateDatabase ``` to  ```false``` → still not working

The difference is FROST only successfully initialize while it's manually send GET Request by using browser. If it's send by program it will keep responding log as below:

```
13:05:32.180 [http-nio-8080-exec-2] INFO     d.f.i.i.f.p.p.ResultBuilder - Failed to run query:
select "e0"."ID", "e0"."PROPERTIES", "e0"."NAME", "e0"."DESCRIPTION" from "THINGS" as "e0" order by "e0"."ID" asc offset 0 rows fetch next 101 rows only
13:05:32.180 [http-nio-8080-exec-2] ERROR      d.f.i.i.f.service.Service - Failed to handle request (details in debug): Failed to run query: Cannot execute query. No JDBC Connection configured
```

**Comment by hylkevds** [comment]
Then you're either starting FROST before the database server is ready, or you misconfigured the database connection.

**Comment by smilehappy126** [comment]
The docker-compose.yml is configured as tutorial:
```
version: '3'

services:
  web:
    build: ./sta_server ##以相對路徑build images
    restart: unless-stopped
    container_name: ${container_name} ##Should be unique
    environment:
      - serviceRootUrl=${serviceRootUrl}
      - http_cors_enable=${http_cors_enable}
      - http_cors_allowed.origins=*
      - persistence_db_driver=${persistence_db_driver}
      - persistence_db_username=${POSTGRES_USER}
      - persistence_db_password=${POSTGRES_PASSWORD}
      - persistence_db_url=${persistence_db_url}
      - persistence_autoUpdateDatabase=${persistence_autoUpdateDatabase}
    ports:
      - ${TOMCAT_PORTS_LOCAL}:${TOMCAT_PORTS_VIRTUAL}
      - ${TCP_PORTS_LOCAL}:${TCP_PORTS_VIRTUAL}
    depends_on:
      - ${PG_ALIAS}
      
  postgrel_database:
    image: postgis/postgis:latest
    restart: unless-stopped
    container_name: ${PGContainer_name} ##Should be unique
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/tmp
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
    ports:
        - ${PG_PORTS_LOCAL}:${PG_PORTS_VIRTUAL}
    volumes:
      - postgis_volume:/var/lib/postgresql/data/postgrel_database
volumes:
    postgis_volume:
```

if there's 'depends_on', it should control the order to initialize i guess.
Because the docker-compose output is well-ordered, server before database:
```
Container sta_lamdr_PG  Created
 Container sta_lamdr  Creating
 Container sta_qtayx  Created
 Container sta_2oxyh  Created
 Container sta_2oxyh_PG  Starting
 Container sta_qtayx_PG  Starting
 Container sta_lamdr  Created
 Container sta_lamdr_PG  Starting
 Container sta_lamdr_PG  Started
 Container sta_lamdr  Starting
 Container sta_2oxyh_PG  Started
 Container sta_2oxyh  Starting
 Container sta_qtayx_PG  Started
 Container sta_qtayx  Starting
 Container sta_lamdr  Started
```
