### ISSUE TITLE
filtering with any problem

### ISSUE THREAD

**Issue by mydeveloperplanet** [FraunhoferIOSB/FROST-Server#1943]
When using the online STA, I can create a MultiDatastream:
```
{
  "Thing": {"@iot.id": 1},
  "Sensor": {"@iot.id": 1},
  "ObservedProperties":  [{"@iot.id": 1},{"@iot.id": 2},{"@iot.id": 3}],
  "name": "temperature, RH, visibility",
  "description": "This is a MultiDatastream from a simple weather station measuring air temperature, relative humidity and visibility",
  "observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_ComplexObservation",
  "multiObservationDataTypes": [
    "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
    "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
    "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_CategoryObservation"
  ],
  "unitOfMeasurements": [
    {
      "name": "degree Celsius",
      "symbol": "°C",
      "definition": "http://unitsofmeasure.org/ucum.html#para-30"
    },
    {
      "name": "percent",
      "symbol": "%",
      "definition": "http://unitsofmeasure.org/ucum.html#para-29"
    },
    {
      "name": "null",
      "symbol": "null",
      "definition": "null"
    }
  ],
  "observedArea": {
    "type": "Polygon",
    "coordinates": [
      [
        [100, 0], [101, 0], [101, 1], [100, 1], [100, 0]
      ]
    ]
  },
  "phenomenonTime": "2014-03-01T13:00:00Z/2015-05-11T15:30:00Z",
  "resultTime": "2014-03-01T13:00:00Z/2015-05-11T15:30:00Z"
}  
```
Querying this with the any operator, returns this MultiDatastream:
https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/MultiDatastreams?$filter=(ObservedProperties/any(op0: op0/definition eq 'http://dd.eionet.europa.eu/vocabularyconcept/aq/meteoparameter/54')) and (ObservedProperties/any(op1: op1/definition eq 'https://qudt.org/vocab/quantitykind/Height'))

However, using a local version of Frost (started with docker compose), the query returns an http 404 response when any is being used.
The docker compose settings are:
```
  frostweb:
    image: fraunhoferiosb/frost-server:2.0
    environment:
    - serviceRootUrl=http://localhost:8090/FROST-Server
    - plugins.multiDatastream.enable=true
    - http_cors_enable=true
    - http_cors_allowed_origins=*
    - persistence_db_driver=org.postgresql.Driver
    - persistence_db_url=jdbc:postgresql://frostdb:5432/sensorthings
    - persistence_db_username=sensorthings
    - persistence_db_password=dummypass
    - persistence_autoUpdateDatabase=true
    ports:
    - 8090:8080
    - 1885:1883
```

Do we need to enable anything in order to be able to use any in a filter?
