### ISSUE TITLE
Incomplete Datastream fields when using $expand parameter in MQTT subscription

### ISSUE THREAD

**Issue by sbraeunleinmainova** [FraunhoferIOSB/FROST-Server#2149]
**Bug Description**
When subscribing to `v1.1/Observations?$expand=Datastream` via MQTT, the Datastream object in the response contains only the ID and selfLink fields, rather than the complete Datastream information.

**Current Behavior**
The MQTT message received contains a Datastream object with minimal information:

```
{
  "@iot.selfLink": "https://server/v1.1/Observations(90213403)",
  "@iot.id": 90213403,
  "phenomenonTime": "2025-04-10T08:44:13.28Z",
  "resultTime": null,
  "result": 3791,
  "Datastream": {
    "@iot.selfLink": "https://server/v1.1/Datastreams(103111)",
    "@iot.id": 103111
  },
  "Datastream@iot.navigationLink": "Observations(90213403)/Datastream",
  "FeatureOfInterest@iot.navigationLink": "Observations(90213403)/FeatureOfInterest"
}
```

Subscribing to `v1.1/Observations?$expand=Datastream($select=description)` results in an empty Datastream.

**Expected Behavior**
The Datastream object should include all fields such as name, description, etc.

**Steps to Reproduce**
Subscribe to v1.1/Observations?$expand=Datastream
POST an Observation

**Environment**
Application Version: 2.5

**Comment by hylkevds** [comment]
Thanks for the report, I'll look into it.

**Comment by hylkevds** [comment]
Which exact version of 2.5 are you using? I can't seem to reproduce it in the latest.

**Comment by sbraeunleinmainova** [comment]
Thank you for looking into this. I am using the following versions:

http:
`{
  "image": "docker.io/fraunhoferiosb/frost-server-http:2.5",
  "imageID": "docker.io/fraunhoferiosb/frost-server-http@sha256:b32020dad24278d09063f268f7ab415c1fdff3a170eb1d39d22131af496275d1"
}`

mqtt:
`{
  "image": "docker.io/fraunhoferiosb/frost-server-mqtt:2.5",
  "imageID": "docker.io/fraunhoferiosb/frost-server-mqtt@sha256:770afd9e49b229fc78be5d7ae5bcf2e60320657187b96f6e331be851c84b1a61"
}`

bus:
`{
  "image": "docker.io/library/eclipse-mosquitto:1.5.11",
  "imageID": "docker.io/library/eclipse-mosquitto@sha256:a969883d583a7cc3dbb0886d9a2d7ad4f776d792b01df9f0bef86a68dca9d08d"
}`

**Comment by hylkevds** [comment]
When you start FROST it will put its exact version number and commit in the log. What is that number for you?

**Comment by sbraeunleinmainova** [comment]
Version number is 2.5.6

**Comment by hylkevds** [comment]
Can you post the configuration or, even better, the starting-logs of the MQTT pod?

**Comment by sbraeunleinmainova** [comment]
Sure. Here is the configuration and the starting logs of the MQTT pod

```yaml
serviceRootUrl:                                     https://<removed>:443/context/sensorthings
alwaysOrderbyId:                                    true
logSensitiveData:                                   false
queueLoggingInterval:                               0
defaultCount:                                       false
defaultTop:                                         100
maxTop:                                             10000
maxDataSize:                                        25000000
useAbsoluteNavigationLinks:                         false
mqtt_mqttServerImplementationClass:                 de.fraunhofer.iosb.ilt.sensorthingsserver.mqtt.moquette.MoquetteMqttServer
mqtt_Enabled:                                       true
mqtt_Port:                                          1883
mqtt_Host:                                          0.0.0.0
mqtt_internalHost:                                  localhost
mqtt_WebsocketPort:                                 9876
mqtt_WaitForEnter:                                  false
mqtt_QoS:                                           2
mqtt_SubscribeMessageQueueSize:                     10000
mqtt_SubscribeThreadPoolSize:                       20
mqtt_CreateMessageQueueSize:                        10000
mqtt_CreateThreadPoolSize:                          10
mqtt_maxInFlight:                                   50
mqtt_exposedEndpoints:                              
mqtt_javaKeystorePath:                              
mqtt_keyManagerPassword:                            
mqtt_keyStorePassword:                              
mqtt_persistentStoreType:                           memory
mqtt_secureWebsocketPort:                           
mqtt_session_queue_size:                            1024
mqtt_session_timeout_seconds:                       3600
mqtt_sslPort:                                       
mqtt_netty_mqtt_message_size:                       8092
bus_mqttBroker:                                     tcp://frost-server-frost-server-bus:1883
bus_busImplementationClass:                         de.fraunhofer.iosb.ilt.sta.messagebus.MqttMessageBus
bus_topicName:                                      FROST-Bus
bus_qosLevel:                                       2
bus_sendWorkerPoolSize:                             10
bus_sendQueueSize:                                  2000
bus_recvWorkerPoolSize:                             10
bus_recvQueueSize:                                  2000
bus_maxInFlight:                                    2000
persistence_db_jndi_datasource:                     
persistence_db_driver:                              org.postgresql.Driver
persistence_db_url:                                 jdbc:postgresql://central-db.dev-database-stack.svc.cluster.local:5432/frost
persistence_persistenceManagerImplementationClass:  de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.PostgresPersistenceManager
persistence_countMode:                              FULL
persistence_idGenerationMode:                       ServerGeneratedOnly
persistence_db_conn_max:                            10
persistence_db_conn_idle_max:                       10
persistence_db_conn_idle_min:                       10
persistence_db_username:                            <set to the key 'db.username' in secret 'frost-server-frost-server'>  Optional: false
persistence_db_password:                            <set to the key 'db.password' in secret 'frost-server-frost-server'>  Optional: false
plugins_plugins:                                    
plugins_coreModel_enable:                           true
plugins_coreModel_editableDsProperties:             false
plugins_coreModel_idType:                           LONG
plugins_modelLoader_enable:                         true
plugins_modelLoader_modelPath:                      
plugins_modelLoader_modelFiles:                     
plugins_modelLoader_liquibasePath:                  
plugins_modelLoader_liquibaseFiles:                 
plugins_modelLoader_securityPath:                   
plugins_modelLoader_securityFiles:                  
plugins_dataArray_enable:                           true
plugins_csv_enable:                                 true
plugins_geojson_enable:                             true
plugins_batchProcessing_enable:                     true
plugins_odata_enable:                               true
plugins_openApi_enable:                             true
auth_allowAnonymousRead:                            true
auth_authenticateOnly:                              true
auth_db_jndi_datasource:                            
auth_db_driver:                                     org.postgresql.Driver
auth_db_url:                                        jdbc:postgresql://central-db.dev-database-stack.svc.cluster.local:5432/frost
auth_autoUpdateDatabase:                            true
auth_db_conn_max:                                   10
auth_db_conn_idle_max:                              10
auth_db_conn_idle_min:                              10
auth_db_username:                                   <set to the key 'db.username' in secret 'frost-server-frost-server'>  Optional: false
auth_db_password:                                   <set to the key 'db.password' in secret 'frost-server-frost-server'>  Optional: false
auth_provider:                                      de.fraunhofer.iosb.ilt.frostserver.auth.keycloak.KeycloakAuthProvider
auth_keycloakConfigUrl:                             https://<removed>/auth/realms/dev/clients-registrations/install/api-access
auth_keycloakConfigSecret:                          <removed>
FROST_LL:                                           INFO
FROST_LL_parser:                                    INFO
FROST_LL_queries:                                   INFO
FROST_LL_requests:                                  INFO
FROST_LL_service:                                   INFO
FROST_LL_settings:                                  INFO
FROST_LL_io_moquette:                               INFO
FROST_LL_liquibase:                                 INFO
FROST_LL_org_jooq:                                  INFO
auth_registerUserLocally:                           true
auth_mqtt_topicAllowList:                           ^/[a-zA-Z0-9_-]+\((('[^']+')|([0-9]+))\)/[a-zA-Z0-9_-]+$
auth_userRoleDecoderClass:                          de.fraunhofer.iosb.ilt.frostserver.plugin.projects.ProjectRoleDecoder
persistence_idGenerationMode_Role:                  ClientGeneratedOnly
persistence_idGenerationMode_User:                  ClientGeneratedOnly
plugins_modelLoader_idType_Role:                    STRING
plugins_modelLoader_idType_User:                    STRING
plugins_projects_enable:                            true
```


[mqtt_pod_startup.log](https://github.com/user-attachments/files/19865163/mqtt_pod_startup.log)
