### ISSUE TITLE
Docker-compose: Error when changing serviceRootURL

### ISSUE THREAD

**Issue by BWibo** [FraunhoferIOSB/FROST-Server#235]
Hey there, 

when I run FROST using the latest `docker-compose` provided [here](https://raw.githubusercontent.com/FraunhoferIOSB/FROST-Server/master/scripts/docker-compose.yaml) and change `serviceRootUrl` config parameter in `docker-compose.yml` to anything else than `http://xxx.xxx.de/FROST-Server`, e.g. `http://xxx.xxx.de/frost` I get this error when browsing to `http://xxx.xxx.de/frost`:

```
HTTP Status 404 – nicht gefunden

Type Status Report

Beschreibung The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/8.5.56
```
Is ist generally not possible to change the sub-URL where FROST is reachable or am I doing something wrong here?

Thanks in advance for your help.

Example `docker-compose.yml` where there service should be available at `http://myExampleHost:8080/frost`:
``` yml
version: '2'

services:
  web:
    image: fraunhoferiosb/frost-server:latest
    environment:
      - serviceRootUrl=http://myExampleHost:8080/frost
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      - database

  database:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data
volumes:
    postgis_volume:
```

**Comment by hylkevds** [comment]
The service root url has to point to the url under which FROST-Server is reachable from the outside. It is what FROST uses to generate navigation links. This setting is used when FROST-Server is behind a reverse proxy that it has no influence over.

The setting has to reflect how the server is reachable from the outside, it does not have any influence on how the Server is reachable from the outside.

**Comment by BWibo** [comment]
OK, thank you, now it's clear. Here is how I realized it using `nginx` as reverse proxy.
This config does not include the MQTT interface.

`docker-compose.yml`
``` yml
version: '2'

volumes:
    frost_postgis_volume:

services:
  web:
    image: fraunhoferiosb/frost-server:latest
    environment:
      - serviceRootUrl=https://myDomain.de/frost
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensoradmin
      - persistence_db_password=changeMe
      - persistence_autoUpdateDatabase=true
      - persistence_alwaysOrderbyId=true
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      - database
    restart: always

  database:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensoradmin
      - POSTGRES_PASSWORD=changeMe
    volumes:
      - frost_postgis_volume:/var/lib/postgresql/data
    restart: always
```

Nginx website config: `/etc/nginx/sites-available/myDomain`

``` txt
server {
        server_name myDomain.de;

   # ....
   # ....

    # FROST-Server (running on Docker) !! Slashed are important! !!
    location /frost/ {
      proxy_pass          http://127.0.0.1:8080/FROST-Server/;
      proxy_redirect      http://127.0.0.1:8080 https://myDomain.de;
      proxy_read_timeout  240;

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
    }

   # ....
   # ....
}

```
