### ISSUE TITLE
Problem with running latest docker images

### ISSUE THREAD

**Issue by JungHam** [FraunhoferIOSB/FROST-Server#265]
Dear developers,
I have a problem with new docker images. 

![image](https://user-images.githubusercontent.com/7046588/90873466-2cf6c680-e3d9-11ea-8f6a-7623669e3f17.png)

This is error message and my docker-compose.yml is below.
```
version: '2.2'

 

services:
  web:
    image: fraunhoferiosb/frost-server:latest
    user: root
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      - database

 

  database:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    ports:
        - 25432:5432
    volumes:
      - postgis_volume:/var/lib/postgresql/data
volumes:
    postgis_volume:
```

My docker desktop community is 2.3.0.3, and for windows 10. 
Could you give me an advice?
I really appreciate with the latest advice you gave me 👍
