### ISSUE TITLE
implement liveness and readyness probes

### ISSUE THREAD

**Issue by StefanSchuhart** [FraunhoferIOSB/FROST-Server#269]
Although the FROST-Server pods in our cluster proved to be stable in the long-run, sometimes we face issues where a http or mqtt Pod becomes unresponsive but the container process was not terminated. 

To detect unresponsive http/mqtt pods and kill them the helm chart should implement liveness und readyness probes for each.

**Comment by phertweck** [comment]
You're right the liveness and readyness probes are currently missing.

We will add them in the future. Anyhow pull requests are very welcome :-)

**Comment by StefanSchuhart** [comment]
After further investigating on this topic [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) and [here](https://blog.colinbreck.com/kubernetes-liveness-and-readiness-probes-how-to-avoid-shooting-yourself-in-the-foot/) its seems to me that implementing a liveness probe is as simple as adding
```yaml
livenessProbe:
  httpGet:
    path: /
    port: somePort
  initialDelaySeconds: 60
  periodSeconds: 20
  failureThreshold: 1
```
to the container spec. But for the readyness probe there should be a distinct service path to check if a pod is busy. 

Could you please confirm my findings?
