### ISSUE TITLE
Cannot create PoolableConnectionFactory

### ISSUE THREAD

**Issue by rlhochpass** [FraunhoferIOSB/FROST-Server#339]
Hello,

i have a problem with my FROST-Server initialisation.
On an Ubuntu Server (20.04. LTS) i have the FROST-Servers's HTTP-Packet in a tomcat and the database is in a docker container. (The web service may not be dockered.)

When I edit the docker-compose.yaml for the web service and the xml-files for the tomcat, i go to FROSTURL/FROST-Server/DatabaseStatus to init my database. 
There is the error: 

```
Back...
de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerLong

Failed to initialise database:
Cannot create PoolableConnectionFactory (The connection attempt failed.)

```

After pressing the button:
```
Updating Database
de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerLong

Failed to initialise database:
Cannot create PoolableConnectionFactory (The connection attempt failed.)

```

If I look at the database with PG-Admin, i see that the tables of the database "sensorthings" are missing. 

***********************************************************************************************************
My configuration: 

 
The extract from docker-compose.yaml:

  ```
environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
```

Tomcat Deployment: 

I edit the .../tomcat/webapps/FROST-Server/META-INF/context.xml with the Resource: 

[...]
   ```
 <Resource
        name="jdbc/sensorthings" auth="Container"
        type="javax.sql.DataSource" driverClassName="org.postgresql.Driver"
        url="jdbc:postgresql://database:5432/sensorthings"
        username="sensorthings" password="ChangeMe"
        maxTotal="20" maxIdle="10" maxWaitMillis="-1"
        defaultAutoCommit="false"
    />
</Context>
```

I see with docker exec on a a full docker implementation, that the server.xml isn't edited.

Did anybody see a mistake? Thanks
