### ISSUE TITLE
Unable to publish via MQTT from separate container

### ISSUE THREAD

**Issue by gamesbook** [FraunhoferIOSB/FROST-Server#415]
I have deployed a FROST server instance using the Docker approach outlined in https://fraunhoferiosb.github.io/FROST-Server/deployment/docker.html - I can add the test data and all looks fine.  My main change is to use port 1884, not 1883.

I can also run some Python test code (using paho client) on my machine to publish data:
```
import datetime
import json
import paho.mqtt.client as mqtt

client = mqtt.Client(client_id="sensor-things")
client.connect(host="hermes", port=1884, keepalive=60)

now = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
data = {'result': 18.81, 'phenomenonTime': now}
payload = json.dumps(data)

client.publish(topic='v1.1/Datastreams(1)/Observations', payload=payload)
```
This also works as expected (in the above example 'hermes' is the name of my machine)

My scenario is that I have publishing code set up in another separate container. However when I run the above script inside that container I get this error:
```
  File "test_st.py", line 6, in <module>
    client.connect(host="hermes", port=1884, keepalive=60)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
(**Note** I can successfully ping "hermes" from within the container.)

What other configuration do I need to allow MQTT publishing in this scenario?

**Comment by hylkevds** [comment]
Did you actually expose port 1884 on the container that runs the FROST-MQTT instance?

**Comment by gamesbook** [comment]
I used the port mapping:
```
    ports:
      - 8081:8080
      - 1884:1883
```
How else should it be done?

**Comment by hylkevds** [comment]
Using that, for connections between containers in the same docker-compose file, you still have to use 1883. 1884 is only for connections from outside of the docker network.
If that doesn't work please post your entire docker-compose file (without passwords) so we can actually see what you are trying to do.

**Comment by gamesbook** [comment]
I am not trying to connect between two containers in the same compose file; its a completely separate container created by a completely different compose.

Here is the one for FROST:
```
version: '2'

services:
  web:
    image: fraunhoferiosb/frost-server:latest
    environment:
      - serviceRootUrl=http://localhost:8081/FROST-Server
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=*****
      - persistence_autoUpdateDatabase=true
    ports:
      - 8081:8080
      - 1884:1883
    depends_on:
      - database

  database:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=*****
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
    postgis_volume:
```
