### ISSUE TITLE
Database not created?

### ISSUE THREAD

**Issue by EOSIT** [FraunhoferIOSB/FROST-Server#60]
I am trying  to build an example instance of the FROST system (server plus DB).  My .yml file looks like this:
```
version: '2'

services:
  web:
    image: fraunhoferiosb/frost-server:latest
    ports:
      - 8081:8080
      - 1884:1883
    depends_on:
      - database

  database:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "7432:5432"
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
    postgis_volume:
```
The build and startup seems OK, but when I login to the database server as user `sensorthings`, and try to display databases/tables, I do not see any of the SensorThings tables and only get this:
```
You are now connected to database "sensorthings" as user "sensorthings".
sensorthings=# \dt
                    List of relations
 Schema |           Name           | Type  |    Owner     
--------+--------------------------+-------+--------------
 public | spatial_ref_sys          | table | sensorthings
 tiger  | addr                     | table | sensorthings
```
Is there a known problem here and/or what needs to happen to ensure the database is properly created?

**Comment by hylkevds** [comment]
Did you browse to `<servername>/FROST-Server/DatabaseStatus` and click the upgrade button?

**Comment by EOSIT** [comment]
Thanks, I just tried that, and I get:

```
Servlet DatabaseStatus at /FROST-Server
Updating Database

Failed to initialise database:
Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "sensorthings")

Done. Back...
```

**Comment by hylkevds** [comment]
If you change the password on the postgis container you also have to configure the FROST-Server (web) container to use that password:
```
version: '2'

services:
  web:
    image: fraunhoferiosb/frost-server:latest
    environment:
      - persistence_db_password=mypassword
    ports:
      - 8081:8080
      - 1884:1883
    depends_on:
      - database

  database:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "7432:5432"
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
    postgis_volume:
```

**Comment by EOSIT** [comment]
I get the same error.  I ran the container in the foreground; here is a code snippet from the log:
```
web_1       | 09:37:29.105 [http-nio-8080-exec-1] INFO    d.f.i.ilt.sta.DatabaseStatus - DatabaseStatus Servlet called.
web_1       | 09:37:29.140 [http-nio-8080-exec-1] INFO  d.f.i.i.s.p.p.PostgresPersistenceManager - Setting up DataSource for database connections.
database_1  | 2018-07-19 09:37:29.160 UTC [31] FATAL:  password authentication failed for user "sensorthings"
database_1  | 2018-07-19 09:37:29.160 UTC [31] DETAIL:  Password does not match for user "sensorthings".
database_1  | 	Connection matched pg_hba.conf line 95: "host all all all md5"
web_1       | 09:37:29.163 [http-nio-8080-exec-1] ERROR d.f.i.i.s.p.p.l.PostgresPersistenceManagerLong - Could not initialise database.
web_1       | java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "sensorthings")
```

**Comment by mjacoby** [comment]
I had a similar problem today with adding environment variables to the docker-compose file and in my case it was resolved by stopping and removing the docker containers (using `docker-compose down`, `docker container ls -a` to list all containers, `docker container rm [container_id]` to remove a docker container) as well as removing the docker images (`docker image ls -a` to list images, `docker image rm [image name]' to remove an image) and then running a clean `docker-compose up`

Maybe this also works for you.

**Comment by EOSIT** [comment]
@mjacoby Thanks; I tried all that but without success.

**Comment by hylkevds** [comment]
Try adding all database parameters:
```
version: '2'

services:
  web:
    image: fraunhoferiosb/frost-server:latest
    environment:
      - persistence_db_jndi_datasource=
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=mypassword
    ports:
      - 8081:8080
      - 1884:1883
    depends_on:
      - database

  database:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
    postgis_volume:
```

**Comment by EOSIT** [comment]
I have tried this also without success.

I then installed the psql client inside the server container and tried connecting to the database container:
```
   psql -h hostname -U sensorthings -p 7432
```
I was able to connect successfully; so the database is accessible and reachable with the current params.

What else should I change/try?

**Comment by hylkevds** [comment]
please post the exact docker-compose.yaml file that you used.

**Comment by EOSIT** [comment]
My `docker-compose.yml ` file:

```
version: '2'

services:
  web:
    image: fraunhoferiosb/frost-server:latest
    environment:
      - persistence_db_jndi_datasource=
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:7432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=sensor
    ports:
      - 8081:8080
      - 1884:1883
    depends_on:
      - database

  database:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=sensor
    ports:
      - "7432:5432"
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
    postgis_volume:
```
